apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-security
  namespace: backend-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-security
  template:
    metadata:
      labels:
        app: sb-security
    spec:
      containers:
        - name: sb-security
          image: arribajim/sb-security:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
