pipeline {
    agent any
    
    environment{    
        GIT_CREDENTIALS="jenkins-dev-arribajim"
        ROOT_FOLDER="backend/fileprocessing"
        DOCKER_IMAGE_NAME="fileprocessing"
    }


  stages {
    stage("checking version"){
      steps{
          sh "git --version"
          sh "java -version"
          sh "mvn -version"
          sh "docker --version"
          sh "kubectl version"

      }
    }
    stage("maven clean and package"){
      steps{
          sh '''
            cd ${ROOT_FOLDER}
            export $(cat .env | xargs)
            mvn -DskipTests=true  clean package
            '''
      }
    }
    stage("docker build image"){
      steps{
          sh '''
            cd ${ROOT_FOLDER}
            export $(cat .env | xargs)
            echo 'with def' ${fileprocessing}
            echo ${DOCKER_IMAGE_NAME}
            '''
            script{
              def dockerImage= docker.build "${DOCKER_IMAGE_NAME}"
              dockerImage.push()
            }
      }
    }
  }
}