def rootFolder = "backend/fileprocessing"
def branchName = "main"
def projectName = "fileprocessing"
def dockerImageName = "fileprocessing"
def githubdir="https://github.com/arribajim/poc-fullstack.git"
pipeline {
    agent any
    
    environment{    
        GIT_CREDENTIALS="jenkins-dev-arribajim"
    }


  stages {
    stage("checking version"){
      steps{
          sh "git --version"
          sh "java -version"
          sh "mvn -version"
          sh "docker --version"
          sh "kubectl version"

      }
    }
    stage("maven clean"){
      steps{
          sh '''
            cd {rootFolder}
            export $(cat .env | xargs)
            mvn clean
            '''
      }
    }
  }
}