apiVersion: v1
kind: Secret
metadata:
  name: fileprocessing-api-secret
  namespace: backend-apis
type: Opaque
data:
  file_path: L3RtcC8=
  api_url: aHR0cDovL2xvY2FsaG9zdDo0MjAw
  server_port: ODA4MA==
